/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'stefan' at '7/23/15 7:51 PM' with Gradle 2.5
 *
 * @author stefan, @date 7/23/15 7:51 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
